[book]
authors = ["Wilfrid E. Reeve"]
language = "en"
multilingual = false
src = "src"
title = "Interlingue for Beginners"
description = "Interlingue course for English speakers."

[output.html]
theme = "src/theme"
default-theme = "light"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/occidental-lang/interlingue-for-beginners"
site-url = "/interlingue-for-beginners/"
google-analytics = "UA-151655688-1"

[output.html.fold]
enable = true
level = 0

[build]
build-dir = "docs"